# supervisord configuration file for eval-app
[program:pocketbase]
directory=/home/nnnpooh/eval-app/backend
command=/home/nnnpooh/eval-app/backend/pocketbase serve --http=0.0.0.0:8090
autostart=true
autorestart=true
stderr_logfile=/home/nnnpooh/logs/pocketbase.err.log
stdout_logfile=/home/nnnpooh/logs/pocketbase.out.log
user=nnnpooh
environment=HOME="/home/nnnpooh",USER="nnnpooh"